### ISSUE TITLE
Video begins to seed again when video is played if unchecked

### ISSUE THREAD

**Issue by Duderichy** [webtorrent/webtorrent-desktop#1023]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

webtorrent Version 0.17.1 (0.97.2) 

**What operating system and version?**

macOS Sierra 10.12

**What did you do?**

Began to watch a video, which I had stopped seeding

**What did you expect to happen?**

Video to play and resume at current point, and for the video to _not_ resume seeding

**What actually happened?**

Video played from previous location (as expected) but the video also began seeding again (not expected). When you quit watching the video the box next to it will be checked, and it will have begun seeding again.

**Comment by feross** [comment]
This is an artifact of how we send the video to the `<video>` tag. We're using the `torrent.createServer()` method of the WebTorrent library. So that means we need to re-enable paused torrents when you start playing them.

You're right, though. It's odd behavior. Here's what I think we can do instead:

- If the torrent is complete, start playing it without using the webtorrent library. The code to serve up the file is simple enough: https://github.com/feross/webtorrent/blob/master/lib/server.js

- If the torrent is not complete yet, we potentially need to get data from the network. So **the torrent should be re-enabled.** This is the current behavior.

**Comment by ryan4888** [comment]
+1

**Comment by samholmes** [comment]
+1

**Comment by albe-rosado** [comment]
mine

**Comment by albe-rosado** [comment]
@feross  Hey, I'm working on fixing this issue, I took a look at the link you posted and If I'm not missing something, that is the implementation of the `torrent.createServer()` method. When you say:  

> "If  the torrent is complete, start playing it without using the webtorrent library"
> 

do you mean that you wish the solution replicates that functionality? Wouldn't be easier to better handle the 'wt-stop-server' event? `torrent.createServer()` already serve the files, regardless if are fully downloaded or not, so what do you think about resuming only if the torrent.progress = 1 or something else along the lines?
