### ISSUE TITLE
TypeError: Cannot set property 'status' of undefined

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1036]
**What version of WebTorrent Desktop?** 0.17.2

**What operating system and version?** All

From our telemetry error logs, we picked up this error. It occurred 27 times today.

```
Processes: window, platforms: darwin linux win32, versions: pre-0.12 0.14.0 0.17.0 0.17.1 0.17.2
TypeError: Cannot set property 'status' of undefined
    at TorrentController.torrentMetadata (.../build/renderer/controllers/torrent-controller.js:63:27)
    at EventEmitter.<anonymous> (.../build/renderer/main.js:365:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by Goldob** [comment]
This error seems to appear only under very specific circumstances and I wasn't able to reproduce it. However, here is my theory what happens:

1. A user adds a torrent through magnet link
2. He hits `remove` before the torrent metadata has been downloaded
3. In renderer process, the torrent is removed from list and a `wt-stop-torrenting` message is sent to main process to destroy the related `torrent` object.
4. Before the main process handles the message, it receives torrent metadata. It sends `wt-metadata`.
5. The message is handled in renderer process. An error occurs due to trying to modify non-existent torrent (it has already been removed from list).

This might be right or wrong depending on my understanding of how the event queue works in Electron. In either case, the simplest solution would be to include a null check in `TorrentController.prototype.torrentMetadata()`.
