### ISSUE TITLE
regular torrent upload dont work

### ISSUE THREAD

**Issue by BenmasterTM** [webtorrent/webtorrent-desktop#1164]
Im using the last webtorrent desktop and see the source, I can:
- Download WSS torrents
- Download regular torrents
- Upload WSS torrents (and seed to webclients)

But im unable to share downloaded torrents or local files to regular torrent clients (not webclients)
Its a bug?

**Comment by feross** [comment]
WebTorrent Desktop can share to normal torrent clients, so this sounds like a network or firewall issue. We don't support NAT traversal via UPnP or NAT-PMP like other clients, so that's probably making it harder for external clients to connect to you. 

In the meantime, you can consider static port mapping on your router.
