### ISSUE TITLE
"100% downloaded ↓ 0 B/s ↑ 0 B/s"

### ISSUE THREAD

**Issue by ghost** [webtorrent/webtorrent-desktop#1186]
http://i.imgur.com/uMTuYIK.png
Why is this a thing? The download is 100% completed, and it should not be showing a downloading message. It should probably be telling me something along the lines that my computer is buffering the video because my system is low-spec.

**Comment by Moscarda** [comment]
I see the same thing on nearly each and every torrent for the first 30 seconds or so after its completion.  Not just ↓ 0 B/s ↑ 0 B/s, either, stats all over the place.  But I am positive the files are indeed complete, I've never once experienced corruption or incompletion from opening a file at 100% even though it was still being shown as downloading.  I can also confirm this has nothing to do with audio/video buffering, because I see it all the time and very rarely use WebTorrent for streaming.

**Comment by feross** [comment]
The message gets printed anytime the video is stalled for any reason, even if it has nothing to do with downloading. We should probably more intelligent about the message we show.
