### ISSUE TITLE
WebTorrent Desktop Installation guide for non debian-based Linux distros

### ISSUE THREAD

**Issue by SiliconKite** [webtorrent/webtorrent-desktop#1207]
Downloading WebTorrent Desktop application from the official site results in downloading a .deb package. I am using Fedora so I do not think I can install using this package. From issue #1173 looks like I do not need either to compile from source? Would it be possible to clarify or clearly point to the installation process for non-debian based Linux distros?

**Comment by SiliconKite** [comment]
Guys, any help appreciated here. From https://github.com/webtorrent/webtorrent-desktop/releases I can see a number of other files apart from the .deb package which I can't use in Fedora. Some of them are win32 files, some other I assume they are the source files to be compiled for any other linux distro? I am in Fedora, and I can't find the app via the usual packet manager... Any help appreciated.

**Comment by AshlessCinder** [comment]
You could install it manually:
 1. Download the compiled linux verson 
`WebTorrent-v0.18.0-linux.zip` or `WebTorrent-v0.18.0-linux-ia32.zip` for 32 bit systems
2. Extract the contents of the inner folder(the actual files) to `/usr/share/webtorrent-desktop`
3. link the `WebTorrent` executable to `/usr/bin` like so:
``` bash
sudo ln -s /usr/share/webtorrent-desktop/WebTorrent /usr/bin/webtorrent-desktop
```
4. [Here is a desktop file from the arch user repository](https://aur.archlinux.org/cgit/aur.git/plain/webtorrent-desktop.desktop?h=webtorrent-desktop)
Put this in `/usr/share/applications/webtorrent-desktop.desktop` so that your Desktop Environment can launch webtorrent desktop
5. [Here is an icon from webtorrent.io](https://webtorrent.io/img/WebTorrent.png)
Put this in `/usr/share/icons/hicolor/256x256/apps/webtorrent-desktop.png` so that your Desktop Environment will use it for displaying webtorrent desktop

**Comment by SiliconKite** [comment]
Thanks Ash!
That was easy peasy!
A single phrase explaining this and what the different Linux files are about would be extremely helpful!

**Comment by AshlessCinder** [comment]
Happy to help! :D

I disagree that this should be added to the webtorrent-desktop docs.

If someone needs help with this hopefully they can find this issue, or they can search online for more general instructions on how to install on their specific distribution.
There will probably be a package available on most distros too. The Arch repository has one, and a .deb is provided, so that's most Linux users right there.

These instructions don't just apply to webtorrent-desktop, they are pretty much how you install anything on most linux machines.

If anyone wants to learn more I'd recommend looking up
1. The .desktop file specification
and
2. how /usr/bin works
