### ISSUE TITLE
Send stop on close

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/webtorrent-desktop#1252]
Hi,
sorry if I do not use technically corrects terms or what I'm asking for it is not expected to happens, but I'm quite new to the BT protocol.

I saw that when I close webtorrent-desktop it does not send a "stopping" message to the tracker. Isn't this supposed to happen? Shouldn't it?

Thank you!

**Comment by feross** [comment]
This is supposed to happen, but there's in our implementation there's a timeout of something like 2 seconds in which we'll wait for cleanup. If it takes too long for some reason, then we'll quit the app before the STOP message is sent to the tracker servers.

This shouldn't cause any issues for trackers, since they'll timeout peers from the tracker after a while anyway.
