### ISSUE TITLE
Same file different hash

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/webtorrent-desktop#1253]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.19) (64-bit)

**What operating system and version?**
Windos 10 - 64

Hi, when i seed a file using webtorrent-desktop it prodeces this info-hash:
a538de91156390f7ef718865292680e3850b3626

The same file, shared using Bittorrent, webtorrent-hybrid and webtorrent-cli produces a different info-hash:
adbf0c637ea22c1ddcd4cac5b1b60e8841042c4f
How could it be?

Thank you!

**Comment by Borewit** [comment]
One of the reasons could be that a different block size is used.

**Comment by Ciao121** [comment]
I think you are right. I'm not really inside the torrent protocol. But doesn't this means users will only find seed/peers hashing with the same block size? Shouldn't it be a standard?

**Comment by Borewit** [comment]
Correct, if the info-hash is different, it is from a torrent sharing perspective not the same torrent, even if the underlying data is the same.

The torrent protocol is not designed exchange partial overlapping data between different torrents. The way I see it, is that every torrent is basically a unique sharing initiative. However, if you do create a torrent at two places, using the same identical files, in the same sequence, with the same parameters, it will result in the same info-hash, and they can be considered the same.

Some parameters in the torrent can be changed without impact on the info-hash, like the tracker URL. 

Sharing the same data with different torrents will work fine. If you would publish both torrents in the example you provided, and you download the first torrent with fresh client. You wait until it completes, then you download the second torrent with the different hash, you will see wit will complete without exchanging data. That is because your clients reads the seconds torrents, and detects that the data of the torrent is already present and is identical according to the hashes.

**Comment by Ciao121** [comment]
Thank you very much for the detailed explanation!
