### ISSUE TITLE
Can the download speed improve?

### ISSUE THREAD

**Issue by dcapeletti** [webtorrent/webtorrent-desktop#1290]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)

**What operating system and version?**
Trisquel GNU/Linux 4.4.0-72-generic 64 bits.

**What did you do?**
Open a magnetic link from the Play site of the Zeronet network.

**What did you expect to happen?**
Make the download as fast as with Transmission.

**What actually happened?**
For the same magnetic link, the download is much slower than with Transmission.

If I open the same magnetic link from Transmission and set it to high priority, the download goes much faster, almost 3 times faster. This should certainly be part of this excellent application.
Thanks

**Comment by ogtega** [comment]
![webtorrent-process](https://user-images.githubusercontent.com/10700460/34322862-1c7c538c-e801-11e7-8877-d12440226cd7.png)
![webtorrent-status](https://user-images.githubusercontent.com/10700460/34322866-275e4ecc-e801-11e7-9e1a-dca53a85ec06.png)

I also notices slower download speeds, but strangely enough my system still reports WebTorrent using ~10x more bandwidth.

**Comment by dcapeletti** [comment]
For the same movie, I upload webtorrent desktop and broadcast images so you can compare the download speed. It's very slow, even if it takes a long time.

![speed webtorrent desktop](https://user-images.githubusercontent.com/5890886/34343477-b06180dc-e9ae-11e7-8752-129e76993c7f.png)
However, in transmission, if the speed is set to high priority, it starts fast as soon as it starts.

![speed transmission](https://user-images.githubusercontent.com/5890886/34343476-afc33fd0-e9ae-11e7-8c7f-323a92205590.png)

There should be some control to set the speed just as transmission does. Maybe you could get some useful code from it.

**Comment by speedstyle** [comment]
The issue here is not with the speed controls, but with the underlying network interfaces. Transmission has smarter torrent downloading because

* it connects to each peer with multiple concurrent connections
* it prioritises segments by availability rather than sequence (which is better for downloading the file but bad for streaming)
* it prioritises peers by bandwidth available

Note that in Transmission, if you set the priority to <kbd>High</kbd> and it is the only torrent, it will not download faster. The priority setting is used to determine one torrent's priority over another, not to determine Transmission's priority over other applications.
