### ISSUE TITLE
Firewall permission

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/webtorrent-desktop#1301]
During setup permission to add a firewall rule is asked. The user can choose to allow it or not.
What does it happens in effect if the user deny this permission?

**Comment by davisjackie321** [comment]
Give

**Comment by feross** [comment]
As far as I understand it, the Windows Firewall controls whether or not WebTorrent Desktop is allowed to listen for incoming TCP connections. If allowed, then WebTorrent uses a TCP server to listen for connections from peers.

If this is blocked, then WebTorrent can only make outgoing connections to other peers, but the reverse direction won't work. Peers won't be able to initiate connections to WebTorrent.

There are two checkboxes to choose from, as you can see:

![windows firewall](https://user-images.githubusercontent.com/121766/39909418-9b658818-54a7-11e8-9a16-e7a101cfadc6.png)

For WebTorrent, checking both boxes is safe since we're designed not only to handle connections from people on your local Wi-Fi network but random peers from all over the world, so security is expected to a very high degree.

But in general, allowing an app to listen for connections on the private networks is safer since you generally don't have random people trying to attack your computer from your home Wi-Fi network.

Honestly, this prompt is super confusing and I bet most users don't understand the implications of it either way.
