### ISSUE TITLE
Unusable

### ISSUE THREAD

**Issue by fjeddy** [webtorrent/webtorrent-desktop#1442]
Fresh format of MacOS High Sierra.

Downloading one torrent is making the app freeze, hover buttons don't show, tabbing into the app can take anything from 20 seconds to 2 minutes. Playing a stream is just lagging 2-5 times in every single frame, making it impossible to watch anything.

And as usual, the fan is running full-speed when WebTorrent is running.

Gone from an okish app to complete utter garbage.

**Comment by Borewit** [comment]
As a full time freelance web developer you must know it important to provide sufficient detail in an issue report like the version or commit you experience as _utter garbage_.

You claim it was _ok-ish_ in the past, so I suppose you can narrow when things turned worse for you, I would take the same _fresh format of MacOS High Sierra_ to esnure the _utter garbage_ is not caused by something else.

> lagging 2-5 times in every single frame

I guess you experienced some kind of lag, and the numbers are rounded up a bit to endorse your dissapointment?

> tabbing into the app can take anything from 20 seconds to 2 minutes... And as usual, the fan is running full-speed

This smells like a lot of CPU cycles to me. As a web professional, are you able to figure out where?

**Comment by feross** [comment]
I don't really think we need to entertain an issue from someone showing such overt hostility.
