### ISSUE TITLE
Malicious traffic detected 

### ISSUE THREAD

**Issue by siemvaessen** [webtorrent/webtorrent-desktop#1487]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.20.2

**What operating system and version?**

Mac OS

**What did you do?**

Download of torrent in progress

**What did you expect to happen?**

Download w/o Sophos threat calls

**What actually happened?**

Sophos warning upon download while download in progress, not for all torrents, just some:

Malicious traffic detected: 'C2/Generic-A' at '/Applications/WebTorrent.app/Contents/Frameworks/WebTorrent Helper.app/Contents/MacOS/WebTorrent Helper' (Technical Support reference: 877190748)
--

Relates to #1392

**Comment by mathiasvr** [comment]
Based on [this link](https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/C2~Generic-A.aspx), it appears to happen when detecting network traffic to a C&C server.

My guess is that this is caused by a specific tracker in the torrent.
Have you tried using a different torrent client to see if this is unique to webtorrent?
Can you try to remove trackers to see if this solves the problem?

**Comment by siemvaessen** [comment]
Hi @mathiasvr ~ where/how can I see what trackers are being used? Same alert.

**Comment by mathiasvr** [comment]
Unfortunately, there isn't a straightforward way to list or edit trackers in webtorrent desktop.
You can right click a torrent and click "Copy magnet link to clipboard", and look at the `tr=` entries.

However, it is probably easier if you try a different torrent client where you can view and edit trackers. This way you can also check if the problem also happens in that client.
