### ISSUE TITLE
Not work in China.

### ISSUE THREAD

**Issue by ykla** [webtorrent/webtorrent-desktop#1547]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.98.21) 

**What operating system and version?**
Windows 10 Pro 1709

**What did you do?**
Just downloaded something. 

**What did you expect to happen?**
Download it.

**What actually happened?**
0B/s. It seems everything in China cannot downloaded by webtorrent.

**Comment by ykla** [comment]
![n tgu7kcfw 8 bj vlj](https://user-images.githubusercontent.com/10327999/53566195-7e344a00-3b96-11e9-9cfd-1743857894ed.png)

**Comment by symonxdd** [comment]
Is the issue still there / do you still need help?

**Comment by boojbooj** [comment]
It works

**Comment by zoukun120** [comment]
> It works

how to slove it

**Comment by feross** [comment]
I've seen reports that the torrent protocol is completely blocked in China, but others claim it should work fine. Without additional info, it's not really possible for us to solve this. 
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion and please share any additional information you may learn about this in the future, especially if there's something we can do to fix it.
