### ISSUE TITLE
Option to Change Download Location of an Already Running Torrent

### ISSUE THREAD

**Issue by finnyabraham** [webtorrent/webtorrent-desktop#1563]
In some of the torrent clients(uTorrent, Bittorent etc.), there is option to change the download location for an already running torrent. If will be good to implement that feature.

**How it works in other Torrent Clients?**

1. Stop the torrent manually
2. Set the Download Location
3. Torrent Client will automatically copy the files to the new download location
4. Start the torrent

**How can it be implemented in WebTorrent?**
1. Set Download Location option can be added to the context menu of the torrent that is running
2. When the user select a new download location, WebTorrent will automatically stop the torrent, move the files to the new location and start the torrent

**Comment by feross** [comment]
Thanks for the feature request! 

WebTorrent Desktop values simplicity more than most torrent apps. This sometimes means saying 'No' to good ideas. We try to implement only the most important features that a torrent app needs and make those features as good as possible. We don't want the app to get overloaded with knobs and dials that may only benefit a small percentage of users.

I don't think it makes sense to implement this feature since it would add complexity and benefit only a small number of users. I hope this makes sense!
