### ISSUE TITLE
Paused streaming was started automatically

### ISSUE THREAD

**Issue by shreyasborse** [webtorrent/webtorrent-desktop#1690]
**What version of this package are you using?**
master [53164a0]

**What operating system, Node.js, and npm version?**
Mac Os 10.14.1, Node.js 10.16.3 , npm 6.9.0 

**What happened?**
I stopped seeding manually, started playing a movie; and paused streaming was started automatically.

**What did you expect to happen?**
If I manually pause the streaming, it should not start automatically while playing the video.

**Possible issue**
State of the streaming is reset in the constructor

**Comment by feross** [comment]
> I stopped seeding manually, started playing a movie; and paused streaming was started automatically.

When you say "streaming" was started automatically, I assume you mean that sharing with the torrent network was activated. This is by design, and a requirement in order to ensure that we can fetch the needed pieces of the torrent on demand.

If the torrent is fully downloaded, then we *could* support an option where you just play it without it starting to seed again, but this is not trivial at the moment. There's an issue for that here: https://github.com/webtorrent/webtorrent-desktop/issues/1023
