### ISSUE TITLE
Context menu -> "Save Torrent File As..." not working

### ISSUE THREAD

**Issue by glatze2000** [webtorrent/webtorrent-desktop#1741]
If you want to save a torrent file of an existing video, you can click on the context menu an "Save Torrent File As...", then the File Save Dialog will be opened.

But a click on the save button does not save the torrent file.

Version: webtorrent-desktop develop
OS: iOS and Win7

**Comment by hicom150** [comment]
Checking this issue I found that in electron@7.0.0 they have **deprecated** "Callback-based versions of functions" as `dialog.showMessageBox()`, `dialog.showOpenDialog()` or `dialog.showSaveDialog()`.

So in order to fix this, we should make the following changes:
- [ ] `dialog.showSaveDialog()` with `dialog.showSaveDialogSync()` addresed in #1743 
- [ ] `dialog.showOpenDialog()` with `dialog.showOpenDialogSync()

**Comment by hicom150** [comment]
This issue should be already fixed in `master` 🎉

Thank you every one for the great work! 👍
