### ISSUE TITLE
No .torrent file created

### ISSUE THREAD

**Issue by dolphinkite** [webtorrent/webtorrent-desktop#1803]
**What version of WebTorrent Desktop are you using?**
I'd like to think it is the latest since I only installed it a few minutes ago. Unfortunately, when I click on "About WebTorrent" I get a cropped window that I can't resize and doesn't show the exact version. It's a bad start when you about window isn't working...

**What operating system and version?**
Win10. Up to date.

**What happened?**
Nothing. That's the problem

**What did you expect to happen?**
I guess I expected a .torrent file would be created.
I simply went in "create new torrent from folder", selected a folder that has 540 files (55GB) and clicked "create torrent" and immediately I'm back to the main screen, with no apparent change. Tried it many times. Always the same. 

I tried to simply add a file and that worked. But not for folders.

**Are you willing to submit a pull request to fix this bug?**
??

**Comment by dsernst** [comment]
### Re: About window cutoff

> Unfortunately, when I click on "About WebTorrent" I get a cropped window that I can't resize and doesn't show the exact version.

Thank you for reporting. This was fixed in https://github.com/webtorrent/webtorrent-desktop/pull/1737, but a new binary hasn't been built to ship it yet.


---

### Re: Creating a Torrent

Here's a gif of what happens on my machine when I create a torrent:

![Kapture 2020-05-02 at 16 01 58](https://user-images.githubusercontent.com/6340841/80894285-8a320500-8c8e-11ea-8eec-f0a7b545b47c.gif)

There's not an explicit `.torrent` file created, but you can right click on the new torrent file, and choose `Copy Magnet Link to Clipboard` to share with others.


Are you having a different experience?

**Comment by dsernst** [comment]
Marking closed. Feel free to comment if this is still an issue 🙂
