### ISSUE TITLE
Unable to see content of About WebTorrent Window

### ISSUE THREAD

**Issue by dipankar-majumder** [webtorrent/webtorrent-desktop#1824]
**What version of WebTorrent Desktop are you using?**
0.21.0
![image](https://user-images.githubusercontent.com/39049086/85290607-e5c28700-b4b6-11ea-912c-dd893f860e1c.png)
**What operating system and version?**
Windows 10 v1903
![image](https://user-images.githubusercontent.com/39049086/85289403-07227380-b4b5-11ea-9c13-5214f866b7ac.png)
**What happened?**
I could not see the content of About WebTorrent Window. I tried to resize the window, but I couldn't do it.
![image](https://user-images.githubusercontent.com/39049086/85289673-6e402800-b4b5-11ea-8da1-e30512f2c312.png)
**What did you expect to happen?**
I expect to see Version, Description, License etc. like Information of the WebTorrent.
**Are you willing to submit a pull request to fix this bug?**
Not sure. 🤔

**Comment by dsernst** [comment]
I believe this was fixed by https://github.com/webtorrent/webtorrent-desktop/pull/1737. That [fix shipped with v0.22](https://github.com/webtorrent/webtorrent-desktop/blob/master/CHANGELOG.md#fixed) 2 days ago.

Can you confirm if this is still an issue on the latest version? v0.23 is available at https://webtorrent.io/desktop/ or from in-app auto-updater

**Comment by alxhotel** [comment]
Thanks @dsernst for mentioning the PR.

I can confirm this issue is now fixed (v0.24.0). So closing this issue.
