### ISSUE TITLE
Webtorrent for desktop becomes unstable when downloading large files 

### ISSUE THREAD

**Issue by Vishnu05** [webtorrent/webtorrent-desktop#1877]
I'm using Windows 10, web-torrent v.23 
This issue I'm facing for a long time when I try to download a large size file. Web torrent becomes unstable and it makes my system to become unstable finally the web torrent crashes 

And sometimes it shows 100 to 200mbs for downloading and takes a while to download for 2gigs file 

Issues start with if the file size goes beyond 8gigs(approx) web torrent takes to much of ram and my Disk read and write operation becomes 100% and crashes 

Node version 14, npm 6.14.0

Need some patch update for this fix. 

**What version of this package are you using?**

**What operating system, Node.js, and npm version?**

**What happened?**

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by feross** [comment]
I think this is two issues:

1. This is related to us not having a resource queue https://github.com/webtorrent/webtorrent/issues/1026
2. We use more RAM than we need to for a large files which are downloading quickly because we keep pieces in memory until they're fully downloaded at which point we write them to disk.

**Comment by feross** [comment]
Since there are already issues for these in `webtorrent`, I'm going to close this issue. Feel free to follow along there.
