### ISSUE TITLE
PR: Cache Verification Information periodical or at least when finished

### ISSUE THREAD

**Issue by frank-dspeed** [webtorrent/webtorrent-desktop#1891]
**What version of WebTorrent Desktop are you using?**
dev
**What operating system and version?**
*
**What problem do you want to solve?**
https://github.com/webtorrent/webtorrent-desktop/issues/1890
**What do you think is the correct solution to this problem?**
this
**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by feross** [comment]
Hi there @frank-dspeed. Did you mean to send a PR instead of opening an issue?

**Comment by frank-dspeed** [comment]
@feross it will give a PR i need always a tracking issue as i do a lot of stuff in parallel and i have some people that send stuff to me on regular base i need to plit issue #1890 into smaller steps. If you like you can supply me with some extra background why the client does not download while watching was there any reason for that?

and any good reason why verify step gets not cached?

**Comment by feross** [comment]
> If you like you can supply me with some extra background why the client does not download while watching was there any reason for that?

Are you referring to how other torrents are paused while one is downloading? I think that's so that bandwidth can be conserved for the active torrent?

> and any good reason why verify step gets not cached?

The file can change between WebTorrent Desktop restarts so we want to check it and not just assume it's unchanged.

**Comment by YOUPERT-INC** [comment]
@feross Hi. I'm the one who posted issue #1890 . If you don't mind I will explain 2 cases we want to improve. 
Case A is, if I watch X, app stops downloading other torrents(e.g. Y, Z). Actually stopping download of Y,Z for bandwidth conservation is reasonable tactics to give higher priority to a streaming content. But the problem is, app starts verifying Y,Z whenever a user returns to download panel, which causes HDD overload. So, I think app needs to take either of actions when a user starts watching. 1) to cache download information (or verification information?) when a user starts watching X in order to resume Y,Z without verification 2) to limit or lower download speed of Y,Z 3) to do nothing to Y,Z because there is ample room in bandwidth unexploited by app in most cases.

Case B is, app verifies all torrents at restart if it has been forcefully terminated by OS shutdown or task manager. What I want to propose as a solution is just asking a user whether to save or not as Word or Excel file does whether it's closed in controlled or forceful manner. If selecting save, app saves download information and otherwise, app deletes all downloads.

**Comment by feross** [comment]
> just asking a user whether to save or not as Word or Excel file does whether it's closed in controlled or forceful manner. If selecting save, app saves download information and otherwise, app deletes all downloads.

This isn't something we want to support.

I responded to your other questions in #1890

**Comment by frank-dspeed** [comment]
@YOUPERT-INC why word? or excel? are you still talking about the verification step?

**Comment by YOUPERT-INC** [comment]
@frank-dspeed Case B can be solved either by saving verification information to somewhere in user's storage periodically or by asking user whether to save or not. I think either is fine to users. However, case A needs to be solved by either 1) cache verification information or 2) limit download speed. By the way, I will discard solution 3) here because there can be excessive multiple downloads fully exploiting bandwidth.

**Comment by YOUPERT-INC** [comment]
@frank-dspeed I found a solution for case A. It is built-in option of WebTorrent desktop settings. By checking off "Highest playback priority" I was able to download Y and Z while playing X. Maybe caching verification information will be another good solution for case A. But easy and reasonable solution for me to manage case A seems to be just set "Highest playback priority=off" as default because our app will allow only up to 3 concurrent downloads.

**Comment by frank-dspeed** [comment]
sounds perfect 
cool that i could help

**Comment by YOUPERT-INC** [comment]
@frank-dspeed Hi Frank. webtorrent/webtorrent#903 is precondition to periodically cache verification information? I can't find direct relationship between CPU overload at restart after seeding and HDD overload at restart after downloading because former is caused by RTCPeerConnection while latter is caused by file verification. Please let me know if I'm missing anything from issue 903. Thank you.
