### ISSUE TITLE
WebTorrent stalling on network with active peers.

### ISSUE THREAD

**Issue by dreaddr** [webtorrent/webtorrent-desktop#1925]
**What version of WebTorrent Desktop are you using?**

0.24.0

**What operating system and version?**

Edition	Windows 10 Pro
Version	20H2
Installed on	‎03-‎Feb-‎21
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

**What happened?**

Torrents stall when resuming, there is no force resume so I had to switch to qBittorrent to download the rest. I am an active seeder but I do not see a lot of seeding happening either. 

**What did you expect to happen?**

To not stall, and to have an option to force resume like qBittorrent in case stalling happens for whatever reason. Resume download status and to finish downloading the the file. 

**Are you willing to submit a pull request to fix this bug?**

No. Not sure why this bug is happening in the first place.

**Comment by a4vg** [comment]
Happening on MacOS 10.15.7 (Catalina) too, WebTorrent Version 0.24.0 (0.108.6).

**Steps to recreate:**
1. Pause download
2. Resume download
3. It shows "Verifying", then "Downloading" with the progress bar, file size and number of peers but not the downloading speed. It isn't just a UI issue since it really isn't downloading anything. It shows an uploading speed sometimes though.

**Workaround:**
Go to start streaming and wait. It doesn't matter if the file isn't supported for streaming. After a few seconds, go back to the torrents list and the download speed with the remaining time appears.

Sometimes after doing this the speed download will be veery low (and it isn't my connection or the peers because before pausing it was working fine), so I just paused again and repeat the process.
