### ISSUE TITLE
11 antivirus engines work on the installer.

### ISSUE THREAD

**Issue by AndreyDedov** [webtorrent/webtorrent-desktop#2218]
v0.24.0

Windows 10

https://www.virustotal.com/gui/file/08b97a6a4b5999bd0f0c2f0eb368eb938a16c373999b672db24ea89664d35714

Expected virus-free software lol!

NO!

**Comment by dtantono** [comment]
yes, I want to add this app to winget. But, it got flagged. Is this false alarm? 
![image](https://user-images.githubusercontent.com/29157187/180588283-d904e523-8259-497f-99d8-0c13da0b7a28.png)

**Comment by SamTwining** [comment]
Antivirus software works on heuristics -- it tries to identify malware based on patterns. For reasons you could probably divine, malware sometimes distributes payloads and updates through peer to peer means.

Webtorrent Desktop is open source, so if you have any hesitations, feel free to inspect the code it runs and verify the AV categorization. Unless you have a specific accuation, please close the issue.

**Comment by AndreyDedov** [comment]
> Antivirus software works on heuristics -- it tries to identify malware based on patterns. For reasons you could probably divine, malware sometimes distributes payloads and updates through peer to peer means.
> 
> Webtorrent Desktop is open source, so if you have any hesitations, feel free to inspect the code it runs and verify the AV categorization. Unless you have a specific accuation, please close the issue.

I still have doubts about false positives because the last release v0.24.0 is virustotal clean
https://www.virustotal.com/gui/file/4e908c53f6ffdd5b4dd9a92800816f7ab1cb20669aef17eca1041b87885f71c5

**Comment by SamTwining** [comment]
> I still have doubts about false positives because the last release v0.24.0 is virustotal clean
> https://www.virustotal.com/gui/file/4e908c53f6ffdd5b4dd9a92800816f7ab1cb20669aef17eca1041b87885f71c5

I'm not an active developer of this repository but I've cloned the repo and will be inspecting it -- If you have evidence of malicious code then by all means, please submit it for review. This is a popular repo with dozens of contributors, so the likelihood of something being overtly malicious within the codebase is not impossible but at least unlikely, or highly conspiratorial.

If you don't have something to present other than the false positive, please close this issue until you do.

**Comment by OfficialEsco** [comment]
I did some testing on a clean Virtualbox VM and i cannot find any traces of Adware, however it might be blocked by a strict host system wide DNS or it did not run because it detected a VM.
* First of all [WebTorrentSetup-v0.24.0.exe](https://www.virustotal.com/gui/file/08b97a6a4b5999bd0f0c2f0eb368eb938a16c373999b672db24ea89664d35714) is the latest installer from https://github.com/webtorrent/webtorrent-desktop/releases/download/v0.24.0/WebTorrentSetup-v0.24.0.exe.
  * [WebTorrentSetup-v0.24.0.exe\Update.exe](https://www.virustotal.com/gui/file/c15a2264547e9b81aaaf1b89813a464679a05280db31c030a94dfd0f82f3eb8a?nocache=1) obv clean
  * [WebTorrentSetup-v0.24.0.exe\WebTorrent-0.24.0-full.nupkg](https://www.virustotal.com/gui/file/66e72ca23173ee1d7f3b3ceab71adbdfa0c69d418282af45265524cc3a054a8a?nocache=1) is just flagged as PUA/PUP
  * [WebTorrentSetup-v0.24.0.exe\WebTorrent-0.24.0-full.nupkg\lib\net45\WebTorrent.exe](https://www.virustotal.com/gui/file/9d08f1f0215b0f7e18ca62a54d69c5ce32bf348561a65bd6caf1b10c537cbb02) which can also be found at `%Localappdata%\WebTorrent\app-0.24.0\WebTorrent.exe` is mostly detected as PUP/PUA, however Malwarebytes blocked a connection to 213.34.163.254:50239 and 117.201.196.173:8080
  * [WebTorrentSetup-v0.24.0.exe\WebTorrent-0.24.0-full.nupkg\lib\net45\WebTorrent_ExecutionStub.exe](https://www.virustotal.com/gui/file/2b3e3c8fbfbafb5565e929ef48d6a1e436506cd91d868be38b77ac3bc12a9efa) which is also found at `%Localappdata%\WebTorrent\WebTorrent.exe` is detected as Adware (Fake Popups)
* Secondly https://www.virustotal.com/gui/file/4e908c53f6ffdd5b4dd9a92800816f7ab1cb20669aef17eca1041b87885f71c5 is [WebTorrentSetup-v0.22.0.exe](https://github.com/webtorrent/webtorrent-desktop/releases/download/v0.22.0/WebTorrentSetup-v0.22.0.exe)
* [WebTorrentSetup-v0.23.0.exe](https://www.virustotal.com/gui/file/c989221c4d57cb75f9b82f2d40ef895f0db84d74b8df4a466b77dd39a118bb51) from [WebTorrentSetup-v0.23.0.exe](https://github.com/webtorrent/webtorrent-desktop/releases/download/v0.23.0/WebTorrentSetup-v0.23.0.exe) is also clean
  * [WebTorrentSetup-v0.23.0.exe\Update.exe](https://www.virustotal.com/gui/file/57a2d0467686ced633ad6ba775411ab5b090b744974c2da0c3ef65618a3f31e9?nocache=1) clean
  * [WebTorrentSetup-v0.23.0.exe\WebTorrent-0.23.0-full.nupkg](https://www.virustotal.com/gui/file/32cdf01ed4e53918121acd5386a3ee5f7c82ffd15ff47ad446a798d28f58d327?nocache=1) clean
  * [WebTorrentSetup-v0.23.0.exe\WebTorrent-0.23.0-full.nupkg\lib\net45\WebTorrent.exe](https://www.virustotal.com/gui/file/29e53f4eaf63d3fa7b7f4f5ffbe7e19c41f5648c16be39b5613b1a71f4c3996b?nocache=1) clean, however it does try to access  178.255.168.117:8621
  * [WebTorrentSetup-v0.24.0.exe\WebTorrent-0.24.0-full.nupkg\lib\net45\WebTorrent_ExecutionStub.exe](https://www.virustotal.com/gui/file/6423c7115076b01efccd84cebf6b6f4a546fef3f7bd73559cb709c0d814690b9?nocache=1) clean

WinGet does not manually approve False Positives, contact the AV's to get it unflagged or remove the malicious code which might have gotten implemented in version 0.24.0.

Since its 2 years since the last release, would there be any changes in a new compile?

**Comment by AndreyDedov** [comment]
> * 213.34.163.254:5023
Definitely bad ip. Based in the Netherlands with a home ISP. https://www.abuseipdb.com/check/213.34.163.254
