### ISSUE TITLE
Open image / PDF files within the app

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#432]
_Opening for @origina. Moved from https://github.com/feross/webtorrent/issues/760#issuecomment-212830793_

I think, in general, we want to open up as many file types within the app as possible. Let's do image and PDF files.

**Comment by thepelkus-too** [comment]
Just some notes on this from looking at it over the weekend:

—Opening images is relatively easy, though it does require tweaking some things in the media handling pipeline in a way that suggests that bringing in some kind of per-media strategy objects might be a good way of grouping those concerns and allowing further extensibility.

—Opening PDFs, it turns out, is trickier. From trying to implement / looking at other attempts at using PDFs with Electron, we can't count on native browser handling / browser-bundled plugins for this, so most people seem to be going with PDF.js. I've got some ideas on how to get that worked in, but since I'm still new to Electron, I'm far from sure what the best way is to handle this.

**Comment by feross** [comment]
Thanks for looking into this, @thepelkus-too! Do you have any plans to send a PR?

**Comment by Flet** [comment]
👍 PDF.js

**Comment by thepelkus-too** [comment]
No plans to do a PR yet, sadly. I was having trouble getting it integrated at all, and after doing some poking and prodding, I finally got the first page of a PDF displaying, but there were no controls for zooming, changing pages, etc. There's a chance that there's a way to use the PDF viewer page that ships with the PDF.js lib to get all of that functionality, but I'm not sure how best to do that in the context of an electron app.

That said, I could probably kick out a well-coded ( I mean, what I consider well-coded 😉  ) version of the image display stuff this weekend, if we wanted to break image and PDF into separate issues?

**Comment by feross** [comment]
Sure, send a PR. There are lots of contributors. I'm sure one of us would
be happy to take a look.

Feross
Blog <http://feross.org/> | WebTorrent <https://webtorrent.io/> | Study
Notes <https://www.apstudynotes.org/>

**Comment by saru95** [comment]
@feross I'd like to work on this. If anyone else isn't ?

**Comment by demoneaux** [comment]
@saru95 feel free to work on it! I don't think anyone's doing anything on it so far.

**Comment by saru95** [comment]
@demoneaux On it. Need a few days. Thanks .

**Comment by Flet** [comment]
@saru95 🤘 
Happy to review!  I got about as far as @thepelkus-too did... displaying the first page via a react component... Hope you can make it further! :grin:
