### ISSUE TITLE
If you stop a torrent, then restart the app, torrent progress is missing

### ISSUE THREAD

**Issue by dcposch** [webtorrent/webtorrent-desktop#480]
This is because we don't save torrent (and individual file) progress in `config.json`.

Instead we get progress only for active torrents from the WebTorrent library.

(We send the entire bitfield of which pieces are present, directly from the WebTorrent torrent object, over to the main window process, every second. This has the additional disadvantage of being inefficient.)

**Comment by feross** [comment]
To clarify (since I was confused at first), the way to reproduce this is:

Enable a torrent. Disable it. Witness that the progress for each file shows up:

<img width="500" alt="screen shot 2016-06-03 at 01 37 06" src="https://cloud.githubusercontent.com/assets/121766/15773458/cd3bde2c-292b-11e6-9537-4e05c68180e7.png">

Restart WebTorrent. File progress is missing:

<img width="500" alt="screen shot 2016-06-03 at 01 36 50" src="https://cloud.githubusercontent.com/assets/121766/15773468/da7c7bc8-292b-11e6-80f5-680d421ef545.png">

Starting the torrent again will make the progress show up again.
