### ISSUE TITLE
Autoplay stream links

### ISSUE THREAD

**Issue by anonymlol** [webtorrent/webtorrent-desktop#671]
Clicking on a stream-magnet link (or stream+magnet, whichever will be decided on in #83) should directly launch the player instead of the download view.

What do you think?

**Comment by feross** [comment]
Agreed. Good idea.

**Comment by jcalfee** [comment]
I just noticed the same thing.  I want to re-direct magnetic links in Firefox from Transmission to web-torrent.  So I did some testing:
```bash
webtorrent-desktop$ electron . 'magnet:?xt=urn:btih:...'
```

The first time, this opened the download view if the torrent was new.  The second time it opened webtorrent-desktop with an Error: "Cannot add duplicate torrent"

A command-line feature to start playing an existing entry or to add and start playing a new entry is the goal.

Looking at the code I see the electron IPC API is used to pass events.  This is part of the logic, but I'm getting a little lost here because I'm trying to work backwards from the error message to the source of the event:
```javascript
torrent.on('infoHash', () =>
    ipc.send('wt-infohash', torrent.key, torrent.infoHash))
```

There are a lot of infoHash hits (178 to be exact).  Also I can see this may be a bit complex.  Can you provide a little direction in adding this feature?  I'll attempt to add it and maybe I can submit a PR.
