### ISSUE TITLE
Add feed support

### ISSUE THREAD

**Issue by noamokman** [webtorrent/webtorrent-desktop#856]
Hi everyone,
I wanna add RSS support for webtorrent.

Something pretty basic like entering an rss url, and webtorrent will automatically download all torrents from the feed.
Thought it would probably be more productive to start a discussion before I submit a PR.

What do you think?

**Comment by mathiasvr** [comment]
I don't think many people needs this, maybe it would be better as a plugin (#664)?

**Comment by dcposch** [comment]
I like the idea of adding feeds. We've thought about doing this for version 2:
https://github.com/feross/webtorrent-desktop/issues/831#issuecomment-242252488

I want to make the existing functionality feel solid first, though: https://github.com/feross/webtorrent-desktop/issues/652

--

I think it would be really cool to make some Creative Commons feeds. We would find artists who are willing to release some of their work under an open license, in return for inclusion in the feed. Those feeds would probably replace the default torrents in 2.0, so everyone who installs WebTorrent Desktop would see them.

There's some precedent for this. Wired magazine managed to get some v well known artists to contribute songs to a Creative Commons album. That CD is actually one of our default torrents now: https://creativecommons.org/wired/

For us, rather than trying to get mainstream artists, I think we'd feature indie artists who are not well known. Lots of those people are already giving away their music for free on Soundcloud / Bandcamp and would love the extra exposure.

**Comment by dcposch** [comment]
@noamokman the feeds would *probably* be RSS based but I've also thought about ways we could make them decentralized

**Comment by noamokman** [comment]
@dcposch interesting. as @mathiasvr said, this should probably be a plugin.
We should first implement the plugin system.

**Comment by xKeiro** [comment]
RSS support would be a really big feature for my personal use. If you were to implement RSS please make it persistent, so when a new torrents get added, it would automatically download it.

**Comment by Openmedianetwork** [comment]
I would like this for a seedbox project I am setting up https://github.com/Openmedianetwork/visionOntv/wiki/Seedbox maybe this could be supported in the desktop app - will put a request in there.

**Comment by SHDanielZ** [comment]
Please?

**Comment by feross** [comment]
This is a neat feature request but it's out of scope for WebTorrent Desktop at this time. We want to focus on making the common use cases more reliable first so we can get to a 1.0 release.
