### ISSUE TITLE
Opening WebTorrent in Ubuntu causes computer to freeze

### ISSUE THREAD

**Issue by ghost** [webtorrent/webtorrent-desktop#956]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v16.0

**What operating system and version?**
Ubuntu 16.04

**What did you do?**

Started computer. Opened WebTorrent

**What did you expect to happen?**
Torrents seeding

**What actually happened?**
Entire computer slowed down to the point of being unusable.

This seems to happen especially when you have lots of torrents. The only work-around I have discovered is to open WebTorrent with the internet disconnected, then re-connect the internet .. then re-start every individual torrent. It still slows down the computer, but not as bad, and then the computer speeds up again after a while.

 As I've also stated in previous issues, WebTorrent.Desktop doesn't seem to have a function that automatically restarts torrents after an internet disconnection, either that or it doesn't work.

**Comment by dcposch** [comment]
I've also seen the app slow down a lot, esp right after starting, when a lot of torrents are active.

This is probably an issue in the underlying library.

@feross we probably need those global resource caps soon (limit # of open file descriptors, # of webrtc connections, # of tcp / udp connections)

> WebTorrent.Desktop doesn't seem to have a function that automatically restarts torrents after an internet disconnection

Sounds like a bug, also in the underlying library.

We'll try to get these fixed soon.

**Comment by feross** [comment]
Yep, both known issues.

**Comment by kopy-kate** [comment]
Just wanted to confirm, the problem still persists in version 17.0. :(

I've had to swap WebTorrent.Desktop with bTorrent.xyz for the moment.. the former seems almost unusable if you have more than 10 torrents. I kind of wish that Wt.desktop could borrow from the simplicity of btorrent, or at least, provide an option for a simple list view, particularly for those with slow computers.

Anyway, still looking forward to testing future versions. I do coding myself, so I know the frustration involved. Feedback is vital for progress, nonetheless.

**Comment by kopy-kate** [comment]
Update: Problem persists in 17.1, too.. with no sign of improvement.

I only have 10 torrents, but they literally render my computer unusable as soon as I restart webtorrent. I either have to leave it running overnight so that it can stabilize, or I have to restart my computer, and start WebTorrent with my internet disconnected.. delete all torrents, and add them again one by one.

**Comment by feross** [comment]
@kopy-kate Thank you for all the feedback, and especially for your patience and understanding. That is so rare in GitHub issues, so I really appreciate that.

> I've had to swap WebTorrent Desktop with bTorrent.xyz for the moment.

This is really interesting. So, you're saying that if you put the same exact torrents in bTorrent, the issue goes away? That's good to know. Means that it's something in the desktop app, and not the underlying webtorrent library.

@dcposch It sounds like this could be the IPC progress messages using up a bunch of CPU, which was our original hunch.

**Comment by kopy-kate** [comment]
Actually, now that you remind me - I did have the same problem with Btorrent.xyz, but it manifested itself differently. 

Btorrent.xyz ended up consuming my CPU about 5 hours after I left it running in an open tab, with more than 20 torrents. My computer just gave up .. there were a bunch of pink, yellow and white lines all over the screen, I had to unplug and restart the computer.

This would never happen to me on Transmission or bittorrent. On Bittorrent you could have 10000 torrents open and it won't affect CPU, I think.

**Comment by kopy-kate** [comment]
Also forgot to add, the WebTorrent.D CPU overload ONLY happens during startup. You actually could have hundreds of torrents on WebTorrent.D .. it's only when you restart the program, that's where the trouble begins.

**Comment by feross** [comment]
Related: https://github.com/feross/webtorrent/issues/903

**Comment by kopy-kate** [comment]
I've recently discovered a workaround to the extreme high CPU usage. This is for Ubuntu for now:

1. Go on System Monitor
2. Find the process called 'WebTorrent --type=render --no-sandbox primordial-pipe-token=' that is using the greatest % of CPU.
3. Right-click, change priority to 'Very Low'

I have the feeling that the high CPU usage might have something to do with the Thumbnails that webtorrent desktop renders for every video. I've noticed this because the CPU tends to spike as soon as a torrent has finished downloading. 

Because it has to download every torrent from scratch when you open the program, it forces every video to re-render the thumbnail .. possibly choking the CPU usage as a result.
